cp_iniciales = (
    (
        "Paso 1 - Declaración Testimonial ",
        "Paso 2 - Declaración Testimonial ",
        "Paso 3 - Declaración Testimonial ",
        "Paso 4 - Declaración Testimonial ",
        "Paso 5 - Declaración Testimonial ",
    ),
    (
        "Paso 1 - Funcionarios intervinientes ",
        "Paso 2 - Partes intervinientes ",
        "Paso 3 - Relato del procedimiento ",
        "Paso 4 - Elementos secuestrados y pruebas Elementos secuestrados y pruebas ",
        "Paso 5 - Firmas ",
    ),
)

cp_datos = (
    "Fecha:",
    "Hora:",
    "Funcionario:",
    "Jerarquía:",
    "Dependencia:",
    "Legajo:",
    "FUNCIONARIO INTERVINIENTES DEL ACTA",
    "FECHA Y HORA DEL HECHO Fecha de Inicio:",
    "Hora de Inicio:",
    "Fecha de finalización:",
    "Hora de finalización:",
    "LUGAR DEL HECHO Partido:",
    "Localidad:",
    "Modo de Ingreso:",
    "Latitud:",
    "Calle:",
    "Longitud:",
    "Altura:",
    "Piso:",
    "Departamento:",
    "Lugar Exacto:",
    "Entre:",
    "Descripcion:",
    "CALIFICACIÓN LEGAL DEL HECHO",
    "INSTA A LA ACCIÓN Para delitos de acción pública dependiente de instancia privada Deja constancia de la manifestación respecto a sí insta o no insta la acción:",
)

cp_inv = (
    "INVOLUCRADO - TESTIGO DATOS",
    "INVOLUCRADO - SOSPECHOSO DATOS",
    "INVOLUCRADO - VICTIMA DATOS",
    "INVOLUCRADO - APREHENDIDO DATOS",
    "INVOLUCRADO - TESTIGO DEL PROCEDIMIENTO DATOS",
    "INVOLUCRADO - REPRESENTANTE DATOS",
    "INVOLUCRADO - PERSONA DE CONFIANZA DATOS",
    "DENUNCIANTE DATOS",
    "INVOLUCRADO - DENUNCIADO DATOS",
)

cp_efectos = (
    "AUTOMOTORES Marca",
    "ARMA/S Tipo",
    "ELEMENTOS SECUESTRADOS Tipo",
    "OTROS OBJETOS Tipo",
)

cascaron = {
    "Fecha:": "",
    "Hora:": "",
    "Funcionario:": "",
    "Jerarquía:": "",
    "Dependencia:": "",
    "Legajo:": "",
    "FUNCIONARIO INTERVINIENTES DEL ACTA": "",
    "FECHA Y HORA DEL HECHO Fecha de Inicio:": "",
    "Hora de Inicio:": "",
    "Fecha de finalización:": "",
    "Hora de finalización:": "",
    "LUGAR DEL HECHO Partido:": "",
    "Localidad:": "",
    "Modo de Ingreso:": "",
    "Latitud:": "",
    "Calle:": "",
    "Longitud:": "",
    "Altura:": "",
    "Piso:": "",
    "Departamento:": "",
    "Lugar Exacto:": "",
    "Entre:": "",
    "Descripcion:": "",
    "CALIFICACIÓN LEGAL DEL HECHO": "",
    "INSTA A LA ACCIÓN Para delitos de acción pública dependiente de instancia privada Deja constancia de la manifestación respecto a sí insta o no insta la acción:": "",
}
